### ISSUE TITLE
Ambiguity when using symbol to retrieve canonical transcript

### ISSUE THREAD

**Issue by sandertan** [genome-nexus/genome-nexus#158]
When testing some transcripts with the API for canonical transcripts and transcripts, I noticed that one of my transcripts does not contain any exons in Genome Nexus. When querying Ensembl (hg38 and hg19), it does contain exons. I was wondering if this is a bug or a mismatch between database I'm querying.

`ENST00000581486` is the canonical transcript for `NCOA4` according to Genome Nexus

Ensembl 91 hg38:
https://www.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;g=ENSG00000266412;r=10:46005091-46030714;t=ENST00000581486

Ensembl 75 hg19:
http://feb2014.archive.ensembl.org/Homo_sapiens/Transcript/Exons?db=core;g=ENSG00000266412;r=10:46005091-46030714;t=ENST00000581486

**Comment by inodb** [comment]
@sandertan thanks for reporting! Best is to check raw data files in https://github.com/genome-nexus/genome-nexus-importer/blob/master/data/Makefile#L12

I didn't check whether all transcripts have exon info

**Comment by sandertan** [comment]
Thanks. I checked the source data for creating exons (`ftp://ftp.ensembl.org/pub/grch37/release-91/gff3/homo_sapiens/Homo_sapiens.GRCh37.87.gff3.gz`), and it refers to a different version of `NCOA4`: ENSG00000266412

So there are 2 genes for NCOA4: 

ENSG00000138293, which contains `ENST00000581486`
http://feb2014.archive.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000138293;r=10:51565108-51590734
Prediction Method: Annotation for this gene includes both automatic annotation from Ensembl and Havana manual curation, see article.

ENSG00000266412
http://feb2014.archive.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000266412;r=HG1211_PATCH:46500536-46526162
Prediction Method: Annotation for this gene includes both automatic annotation from Ensembl and Havana manual curation, see article. **This was projected to the alternate locus via a mapping from the primary assembly.**

**Comment by inodb** [comment]
@sandertan ah tricky. It's unfortunate that not all of the transcripts have exon info. What's your use case? Maybe it's ok to use a non-canonical transcript?

**Comment by sandertan** [comment]
I was just testing the API for various scenarios of (canonical) transcripts and gene symbols, with the purpose of using it in the cBioPortal validator for a new data type (structural variants). We're implementing it in such a way that providing the transcript (perhaps non-canonical) in the data is highly recommended. But sometimes the data does not contain the transcript and in those cases, we'd like to retrieve the canonical transcript and its exons.

**Comment by sandertan** [comment]
So ensembl_biomart_transcripts.txt contains:
```
ENST00000581486	ENSG00000266412	NCOA4	ENSP00000462943	614
```
This is consistent with the **current** (hg38) NCOA4 gene:
https://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000266412;r=10:46005088-46030714

Is `ensembl_biomart_transcripts.txt` by any chance made with a BioMart from Ensembl 91 / hg38 instead of BioMart from Ensembl 75 / hg19 ? Do you know the source of this file? Perhaps it's possible to add the source/date/version to the filename.

**Comment by inodb** [comment]
@sandertan it's from hg19. The raw data file does has the version in it https://github.com/genome-nexus/genome-nexus-importer/blob/master/data/Makefile#L6

**Comment by inodb** [comment]
But yes I guess for your use case you could get the canonical transcript. If that lacks exon info - use longest transcript that has exon info

**Comment by sandertan** [comment]
Apologies @inodb , I had mixed things up in the 3rd comment, and fixed it. In summary:

- `Homo_sapiens.GRCh37.87.gff3.gz` only has the old NCOA4 gene:`ENSG00000138293`
- `Homo_sapiens.GRCh37.87.gff3.gz` does not contain transcript:`ENST00000581486`
- `ENST00000581486` is the canonical transcript of the new NCOA4 gene:`ENSG00000266412`
- API `ensembl/canonical-transcript/hgnc` currently returns for `NCOA4`: gene:`ENSG00000266412` and transcript:`ENST00000581486`
- API `ensembl/transcript`  currently returns for `NCOA4`: 
gene:`ENSG00000138293` and a bunch of transcripts, including `ENST00000581486` without transcripts. It's not included in `Homo_sapiens.GRCh37.87.gff3.gz

I'm having trouble putting all these pieces together, but it looks like that the canonical transcript API should return `ENSG00000138293` as the gene for NCOA4, with a different canonical transcript.

**Comment by sandertan** [comment]
Perhaps, because NCOA4 is ambiguous in the GRCh37 Ensembl Release, when querying a HUGO Symbol for a canonical transcript, the API should return all Ensembl gene IDs that are associated with it and include the canonical transcript per ENSEMBL gene ID. 

This will leave it to the user to solve the ambiguity. 

NCOA4 is probably not the only gene with this issue.

**Comment by sandertan** [comment]
I've asked @dionnezaal to help us with this issue.

**Comment by inodb** [comment]
Thanks for going through this @sandertan ! Yeah I'm sure there are a ton of these issues. The canonical transcript list actually comes from here: https://github.com/mskcc/vcf2maf/tree/master/data. There's an isoform overrides list for uniprot and mskcc. That's where the idea of `canonical` transcript comes form. I think for cBioPortal purposes all this really should be is a default. Then the user can indeed work out these type of ambiguities when necessary. 

We could pick a different canonical transcript for `NCOA4` if preferred. Might make sense to pick one that has the exon information in GRCh37. However there are some potential issues with changing this.

The current logic basically picks the longest transcript for each related hugo symbol if it's not in mskcc or uniprot isoform lists. I was planning to add another step to use the hugo gene assignment from genenames.org when available before picking longest transcript (unf not hg19/hg38 specific). There they also use `ENSG00000266412` for `NCOA4`. Of course we should still be able to manually override some when necessary, but would rather keep that to a minimum so the logic remains decently clear.

If we were to apply this logic of selecting only canonical transcripts that have exon information across the board we might end up with canonical transcripts that aren't in the mskcc isoform list. That would not be ideal, since we're trying to be consistent in our annotations with what's produced here by vcf2maf. If following this logic doesn't affect any of the `mskcc` isoforms then it might make sense to do this. Otherwise for your use case it might be better to have the validator retrieve all transcripts for that hugo symbol and pick the longest one that has exon info.

In any case I also don't think we should spend too much time on getting these defaults right. One of the main reasons driving genome nexus is to be able to switch isoforms. A sensible default is important, but we should keep in mind that the user should be able to switch. So if there's no exon information available for that transcript we should just have some message in those features relying on exon info that the exon information is missing and they might want to try another one.

**Comment by sandertan** [comment]
Hi @inodb thanks for explaining.

Indeed, for cBioPortal usage things should be really on default setting. Ideally, users provide the used transcript with the data.

I can prevent this whole issue in my use case by making the transcript ID column a requirement. In that case, the canonical transcript does not have to be retrieved. In the documentation, I can explain users that exons are retrieved from `ftp://ftp.ensembl.org/pub/grch37/release-91/gff3/homo_sapiens/Homo_sapiens.GRCh37.87.gff3.gz` and that they should check if this file contains their transcript with exons.

It may be better to spend our time on other things, like compatibility with GRCh38 and other VEP releases.
