### ISSUE TITLE
local VEP web service

### ISSUE THREAD

**Issue by jjgao** [genome-nexus/genome-nexus#25]
Install a local VEP web service so that we can speed up annotation and control the data version.

**Comment by ckandoth** [comment]
@inodb @jjgao Is this implemented? I see that Genome Nexus now uses `localhost:3000/vep`, which returns `Connection refused` for all queries. Many of the portal imports are erroring out because of this. Here is an [example failure](http://annotation.genomenexus.org/hgvs/4:g.143043362C%3ET?isoformOverrideSource=mskcc&cancerHotspots=summary) to help troubleshoot, and [this example works fine](http://annotation.genomenexus.org/hgvs/X:g.66937331T%3EA?isoformOverrideSource=mskcc&cancerHotspots=summary) because I assume it's cached.

**Comment by inodb** [comment]
@ckandoth Seems like this was used for a bit, but right now it's using ensembl's vep. This is still in progress according to @zheins

**Comment by zheins** [comment]
@inodb Right, but we realized we didn't have all the data sources we needed loaded into our database for it. @angelicaochoa is currently working on updating this. We switched it back to ensembl for now until we get our local instance running again.

**Comment by inodb** [comment]
@angelicaochoa is the local instance running again now?

**Comment by angelicaochoa** [comment]
@inodb not yet - we need to make the aws machine more stable before putting it back in production. Working with admins right now to set up a test server bc the local VEP was taking up too many resources.
