### ISSUE TITLE
Annotation issue: alteration shows as MUTATED

### ISSUE THREAD

**Issue by zhx828** [genome-nexus/genome-nexus#426]
The alteration is annotated as MUTATED but is annotated differently in MPath
Portal link: https://cbioportal.mskcc.org/patient?sampleId=P-0055232-T01-IM6&studyId=mskimpact
MPath: https://cvr.mskcc.org:8083/sample/88866

In case you don’t have the access to MPath, it looks like this. This variant has a level 1 treatment associated.
![Screen Shot 2020-07-02 at 5 12 18 PM](https://user-images.githubusercontent.com/5400599/86412966-14e2b080-bc8e-11ea-9547-07b7650d8f6c.png)

**Comment by inodb** [comment]
@ao508 Looks fine on genome nexus homepage: https://www.genomenexus.org/variant/4:g.55152095_55152107delinsA. I'm guessing a pipeline annotation issue?

Would it be possible to have some check to make sure there are no MUTATED records in the private database?

**Comment by ao508** [comment]
@inodb When I hit the pipelines GN instance, which we just moved to k8s and is using a local vep now, I'm not getting a valid response actually so this might involve some investigating to diagnose what's going on with the local vep/k8s GN. 


cc @sheridancbio @averyniceday 

you can see the query Ino made above - here is the same query but on the pipelines GN app 

http://annotation.genomenexus.org/variant/4:g.55152095_55152107delinsA

Let's discuss tomorrow.

**Comment by inodb** [comment]
Thanks @ao508 !

**Comment by ao508** [comment]
@inodb alright so I found that when the variant data is converted into the genomic location format the start position in the input to the annotator does not match the start position found in the data file itself. 

If we manually construct the genomic location (below) based on the values given in the data file itself we see this:

```
[{
"chromosome":"4",
"start":55152095,
"end":55152107,
"referenceAllele":"ATCATGCATGATT",
"variantAllele":"A"
}]
```

The JSON response however shows a slightly different genomic location in the `annotation_summary` field: (start position is shifted by 1).

```
[{
"chromosome":"4",
"start":55152096,
"end":55152107,
"referenceAllele":"ATCATGCATGATT",
"variantAllele":"A"
}]
```


I suspect it's because the first nucleotide in the ref and var allele is the same? I think I remember seeing some logic that adjusts the start position in such cases. 

Anyway, when we're mapping results from a POST request back to the MAF records from the input file we use the genomic location as a key. Since the genomic location derived from the input MAF does not match exactly the genomic location in the returned JSON `annotation_summary` field, the annotation pipeline is mistakenly believing the annotation actually failed.

**Comment by inodb** [comment]
Thanks @ao508 ! Ah yes this is recurring issue. We're having the same issue on the frontend with on the fly annotation

I think we had some ideas for how to fix this:

1. keep order of variants in POST request. Include empty records with failed annotation flag set to true.
2. include original raw request

I was under the impression @averyniceday and @sheridancbio had implemented something like 1. But maybe it was only the part that sends the variants to VEP in order. Not keeping the order of Genome Nexus POST requests themselves

A quick fix in the annotation pipeline might be to do a GET request for all failed variants, but yeah we should def fix this at the service layer as well

**Comment by jjgao** [comment]
In OncoKB API, we always return the original request which can also include an ID for the variant.

![image](https://user-images.githubusercontent.com/840895/87074329-b0bf6f80-c1ec-11ea-9351-f2fe53283168.png)

**Comment by ao508** [comment]
@jjgao I was thinking the same thing

**Comment by inodb** [comment]
@zhx828 this seems fixed. Thanks @ao508 !

**Comment by zhx828** [comment]
Thank you both! @ao508 @inodb
