### ISSUE TITLE
API calls to OncoKB

### ISSUE THREAD

**Issue by zhx828** [genome-nexus/genome-nexus#437]
I noticed that all the api calls to oncokb are through cbioportal proxy, this may not be a good idea. We should try to not expose that endpoint as much as possible.

The following endpoints are freely accessible, no token needed.
- [ ] /utils/cancerGeneList -> should use https://www.oncokb.org/swagger-ui/index.html#/Cancer%20Genes/utilsCancerGeneListGetUsingGET_1
- [ ] /genes -> should use https://www.oncokb.org/swagger-ui/index.html#/Cancer%20Genes/utilsAllCuratedGenesGetUsingGET_1

The following endpoint requires the authentication
- [ ] /annotate/mutations GN should have a proxy for this endpoint, but I understand if you want to stick with portal one.

I'm not sure why you want to use the search endpoint while the annotate endpoint provides the same response
- [ ] /search

**Comment by leexgh** [comment]
@zhx828 Thanks for checking! It's good to know some of the endpoints are freely accessible, we can replace some of the data by using these endpoints, but GN website also needs more like Therapeutic data.
We could have a proxy for those authentication-needed endpoints, just I'm thinking will that create another endpoint with OncoKB data exposed?
I can't remember exactly why do we use search endpoint, probably it's because cBioPortal uses that endpoint and therefore we use it indirectly? As far as I can see it doesn't have to be search endpoint. BTW I can't find search endpoint on https://www.oncokb.org/swagger-ui/index.html, has it been removed?

**Comment by zhx828** [comment]
@leexgh ideally GN should also come up with a solution for authentication apps used in GN. But for now, you can stick with cbioportal proxy. I'm currently exploring options in OncoKB how to achieve that, once I have a full solution, GN can utilize the similar.
The search endpoint is still there, but hidden by the swagger. We do not suggest using it comparing to endpoints listed on swagger page.

**Comment by leexgh** [comment]
@zhx828 Sounds great, thank you!

**Comment by jjgao** [comment]
@leexgh @inodb we should also integrate the oncokb data in the variant annotation endpoint.

**Comment by jjgao** [comment]
@zhx828 once you implement [reCAPTCHA](https://github.com/oncokb/oncokb/issues/2099), let's switch to the same solution in GN.

For GN API, we should consume the OncoKB public endpoint and integrate them. For the protect endpoints, we should allow the user to supply an API token.

**Comment by zhx828** [comment]
With more usage of genome nexus, we should prioritize this ticket. Here are few suggestions, happy to discuss further:
- GN should not support CORS, so GN cannot be embed. At least for the public GN instances, we should make sure this is the case.
- GN should proxy data trough its own endpoint and add OncoKB token through there. GN local installation should have its own token.
- I still didn't find a better way to protect the proxy from curl calling which does not need to specify the origin or can fake the origins. One possible way is to use reCAPTCHA token. But every api call needs to have different reCAPTCHA token since the token can only be validated once. This creates performance bottleneck.

**Comment by onursumer** [comment]
> With more usage of genome nexus, we should prioritize this ticket. Here are few suggestions, happy to discuss further:
> 
> * GN should not support CORS, so GN cannot be embed. At least for the public GN instances, we should make sure this is the case.

I think this would break mutation mapper library except when we use it on the GN website. We can solve this problem in cBioPortal by using the backend proxy, but we will need another workaround for pure frontend projects like SignalDB.
> * GN should proxy data trough its own endpoint and add OncoKB token through there. GN local installation should have its own token.

👍 
> * I still didn't find a better way to protect the proxy from curl calling which does not need to specify the origin or can fake the origins. One possible way is to use reCAPTCHA token. But every api call needs to have different reCAPTCHA token since the token can only be validated once. This creates performance bottleneck.

This seems to be the most tricky issue to resolve. We can try reCAPTCHA and see how it performs for larger queries, but probably we will need a better solution.

**Comment by jjgao** [comment]
Let's have a discussion soon on this and prioritize it.

**Comment by jjgao** [comment]
Here is my proposal:

On cBioPortal side
- For OncoPrint, directly use OncoKB public API
- For Mutations table, directly use OncoKB public API (need to modify the OncoKB API to add lighest levels, see below)
- For tooltip of Mutations table, i-frame a tooltip from OncoKB (see below)

On OncoKB side
- Add highest level of each (tx, dx, px) to the public API
- Create a tooltip page that can be i-framed by a list of websites
- Local instances of cBioPortal should send their URLs to us in order to add to the list (maybe good idea to associate the url to the user)

**Comment by inodb** [comment]
I guess this is replaced by #9261
