### ISSUE TITLE
PTM sites of BRAF

### ISSUE THREAD

**Issue by jjgao** [genome-nexus/genome-nexus#491]
There are many PTM sites from dbPTM, see http://dbptm.mbc.nctu.edu.tw/info.php?id=BRAF_HUMAN, `Experimental PTM Sites` tab, but not in Genome Nexus: https://www.genomenexus.org/variant/7:g.140453136A%3ET

**Comment by onursumer** [comment]
This seems like an id mapping issue on our side. In https://github.com/genome-nexus/genome-nexus-importer/blob/53b39dceaff7d69c009340605363954bc2f886fe/data/common_input/CCDS2Sequence.current.txt we have two lines for `CCDS5863.1` (which is the CCDS id for BRAF_HUMAN):

```
CCDS5863.1	1	1	NCBI	NM_004333.5	NP_004324.2	Accepted	1
CCDS5863.1	1	1	EBI,WTSI	ENST00000646891.1	ENSP00000493543.1	Accepted	1
```

Currently, genome nexus importer only parses the ids starting with `ENST`: 

https://github.com/genome-nexus/genome-nexus-importer/blob/53b39dceaff7d69c009340605363954bc2f886fe/scripts/add_enst_id_to_ptm.py#L15

Therefore the importer sees `ENST00000646891` as the only valid transcript for BRAF. However, this is not the canonical transcript. Actually, we don't even have this transcript in our transcript dropdown menu. That's why we don't see any PTM sites for BRAF.

I think we need to update the existing logic to accept `NM_004333` as a valid transcript. We may need another mapping from `NM` to `ENST` to make this work because we always query with `ENST` in the frontend like this:

https://v1.genomenexus.org/ptm/experimental?ensemblTranscriptId=ENST00000288602

CC: @inodb
