### ISSUE TITLE
oncokb annotation track is empty for L755S

### ISSUE THREAD

**Issue by inodb** [genome-nexus/genome-nexus#512]
![Screen Shot 2021-04-21 at 10 44 01 AM](https://user-images.githubusercontent.com/1334004/115573209-91329880-a28e-11eb-94ce-c81afec35628.png)
https://www.genomenexus.org/variant/17:g.37880220T%3EC

But it is viewable in cBioPortal:

![Screen Shot 2021-04-21 at 10 43 28 AM](https://user-images.githubusercontent.com/1334004/115573278-9b549700-a28e-11eb-9a3d-d00d81b7e6b2.png)
https://bit.ly/3eiuXf7

**Comment by onursumer** [comment]
Looks like `oncokb/search` and `oncokb/genes` endpoints are failing. It's most likely that those endpoints have been removed/updated. We still use `react-mutation-mapper@0.4.3` which is more than a year old and probably not compatible with the latest OncoKB API anymore.

Updating packages to the latest versions should fix the problem. But we need to update the mobx version and fix related issues as well, because we still use `mobx@3.1.7` in this project.
