### ISSUE TITLE
Add exon information from ensembl

### ISSUE THREAD

**Issue by inodb** [genome-nexus/genome-nexus#84]
Necessary for Fusion Data Visualization in cBoPortal:

https://docs.google.com/document/d/1tzSW2iB59bcns4xNCSJjMTxaX2uavCILDD4lo3HwcE4/edit?ts=5a0092ca#heading=h.t10nr9te3qvu

**Comment by pieterlukasse** [comment]
Instead of loading from FTP site (ftp://ftp.ensembl.org/pub/grch37/release-90/gff3/homo_sapiens/), you could also proxy this service: https://rest.ensembl.org/lookup/id/ENST00000496384?content-type=application/json;expand=1 .It is GRCh38 though. For 37 use: https://grch37.rest.ensembl.org/lookup/id/ENST00000496384?content-type=application/json;expand=1

**Comment by pieterlukasse** [comment]
@dionnezaal can help testing once it is in genomenexus.

**Comment by jjgao** [comment]
Thanks. @pieterlukasse. I like the ensembl service, esp the json is defined.

@pieterlukasse do you think your team can do the implementation? :)

**Comment by pieterlukasse** [comment]
@jjgao we will pick this one up :+1:

**Comment by jjgao** [comment]
@pieterlukasse awesome! Great to have more people on GenomeNexus. @inodb or @onursumer can probably give you a head start.

**Comment by inodb** [comment]
this is finished
